# IBM for ungulate grazing and helminth transmission
# Author: Juan S. Vargas
# Institution: Queen's University Belfast
# Date: September 2025

# The model is based on Fox et al. (2013. PLOS ONE 11:e77996). The model
# seeks to understand how different processes like spatial heterogeneity or
# differences in host susceptibility affect the distribution of parasites among
# host. The code was partially generated by Google gemini.

#--- clear workspace
rm(list = ls())

#---Load libraries
library(doParallel)

#--- Import functions, parameters and initial states
source('Fox2013_IBM.R')

#--- Set up parallel workers
nWorkers<-length(future::availableWorkers())
cl <- makeCluster(nWorkers)
registerDoParallel(cl)

#--- run code in parallel
clusterEvalQ(cl, source('Fox_initCond.R')) # initializing in each core so that initial conditions are not identical
out <- foreach(i=1:nWorkers) %dopar%  run_model()

outname <- paste0("FoxSimOut_", format(Sys.time(), format = "%Y%m%d_%H%M"), ".rds")
saveRDS(out, file = outname)

