# IBM for grazing and helminth transmission
# Author: Juan S. Vargas
# Institution: Queen's University Belfast
# Date: September 2025

# The model is based on Marion et al. (2008. J. Agr. Sci. 146:507). The model
# seeks to understand how different processes like spatial heterogeneity or
# differences in host susceptibility affect the distribution of parasites among
# host. The code was partially generated by AI (Google gemini)

#--- clear workspace
rm(list = ls())

#---Load libraries
library(doParallel)

#--- Import functions 
source('marion2008_gemini_IBM.R')

#--- set parameters
Na <- 3 # N animals
N_patches <-  70*70 # N patches
total_time <- 60*24*100 # total simulation time (in minutes) 
beta <- 0.1  # per-capita feeding rate
gamma <- 0.00004 # sward growth rate
h_max <-  400 # maximum sward height (logistic growth)
h0 <- 50 # ungrazeable portion of sward
s0 <- 2000 # units of feces deposited per defecation event
mu_f <- 0.0025 # livestock feces avoidance parameter
mu_w <- 0 # wildlife feces avoidance parameter
lambda_w <- 0 # rate of decay of wildlife feces
lambda_f <- 0.00001776 #  rate of decay of livestock feces
nu <- 0.015 # intrinsic search/movement rate
alpha <- 10 #  power law search coefficient
f_dep <- 1 # defecation rate

#--- Set up parallel workers
nWorkers<-length(future::availableWorkers())
cl <- makeCluster(nWorkers)
registerDoParallel(cl)

#--- run code in parallel
out <- foreach(i=1:nWorkers) %dopar%
  run_grazing_model(Na, N_patches, total_time, beta, gamma, h_max, h0, s0, mu_f, mu_w,
                         lambda_w, lambda_f, nu, alpha)

outname <- paste0("MarionSimOut_", format(Sys.time(), format = "%Y%m%d_%H%M"), ".rds")
saveRDS(out, file = outname)

